name: AlgoData

on: [push, pull_request]

jobs:
    test:
        strategy:
          matrix:
            go-version: [1.17.x]
            os: [ubuntu-latest,]
        runs-on: ${{ matrix.os }}
        steps:
        - name: Install Go
          uses: actions/setup-go@v2
          with:
            go-version: ${{ matrix.go-version }}
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Generate readmes
          run: |
            go run generaterdm.go
        - name: Commit readmes changes
          run: |
            git config --global user.name 'Github Action'
            git config --global user.email 'josuebrunel@users.noreply.github.com'
            git add . # stage new files and modifications
            git commit -m "Update documentation"
            git push origin master

